 name: CI

 on:
   workflow_dispatch:
     branches:
       - main
 
 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Get Your Code
         uses: actions/checkout@v2

       - name: Say Hello to the World
         run: echo $HELLO
